### ISSUE TITLE
 createTracklogHandler.js: SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-nodejs-backend#3]
webserver sa kvoli tomu nespusti. ale je to zahadne, lebo zatvorky sa zdaju byt sparovane spravne
```
freemap-v3-api/app/routers/tracklogs/createTracklogHandler.js:27
  );
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at global.rootRequire.name (freemap-v3-api/index.js:2:30)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by zdila** [comment]
Upgradni na Node 8.

**Comment by petervojtek** [comment]
updatol som  node na 8.0.0 a dal som `npm i`.

webserver vsak pri spusteni pada, pretoze mu chybaju packages. postupne to pada pretoze chybaju:

```
array-flatten
encodeurl
escape-html
is-buffer
merge-descriptors
... atd
```

asi po piatom chybajucom balicku som to uz dalej neskumal.

**Comment by petervojtek** [comment]
ok, pomohlo uplne zmazanie node_modules a npm i.
